#!/bin/sh

PROJECTROOT=`echo $(cd ${0%/*}/../../ && pwd -P)`/
FIXER=vendor/bin/php-cs-fixer

if [ ! -e ${PROJECTROOT}${FIXER} ]; then
	echo "PHP-CS-Fixer not available, please run composer install"
    exit 1
fi

RES=`php ${PROJECTROOT}${FIXER} fix $PROJECTROOT --verbose`
if [ "$RES" != "" ]; then
	echo "Coding standards are not correct, cancelling your commit."
	echo ""
	echo $RES
	echo ""
	exit 1
fi	
